# Site settings
title: Wise Anser
email: mail@wiseanser.com
description: "The Wise Anser helps you to integrate Getting Things Done (GTD) in your digital workflow."
baseurl: "/blog"
url: "http://wiseanser.com"
twitter_username: wiseanser
github_username:  efelcie

# Build settings
markdown: kramdown
permalink: pretty
